<a href="https://colab.research.google.com/github/RODIV45/Data-Analysis-with-Python-GFG/blob/main/MODEMEANMEDIANnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,9,7,2,0,6,3])
mean=sum(arr)/len(arr)
print(mean)

3.8181818181818183


In [4]:
np.mean(arr)

3.8181818181818183

In [5]:
#weighted average mean
w=np.array([1,2,3,4,5,6])
arr1=np.array([1,3,5,7,9,10])
np.average(arr1,weights=w)

7.380952380952381

In [6]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
np.mean(arr2) #MEAN OF A 2D ARRAY

4.5

In [10]:
np.mean(arr2,axis=1)

array([2.5, 6.5])

In [13]:
np.mean(arr2,axis=0)

array([3., 4., 5., 6.])

In [ ]:
#MEDIAN
#FIRST SORT IN ASCENDING ORDER
#CHECK LENGTH OF ARRAY,LEN=N
#LEN/2==1 ODD OR ==0 EVEN
#IF ODD THE (LEN+1)/2 TH ELEMENT IS THE MEDIAN
#IF EVEN THEN (N/2+N/2 +1)/2


In [33]:
arr3=np.array([1,4,6,7,2,3,7,7,9,4,5,5,7,8,9,0,0,0])
k=np.sort(arr3,axis=0,kind='mergesort')


In [34]:
k

array([0, 0, 0, 1, 2, 3, 4, 4, 5, 5, 6, 7, 7, 7, 7, 8, 9, 9])

In [35]:
np.median(k)

5.0

In [36]:
a=np.median(k)
b=np.mean(k)

In [37]:
np.mean(k)

4.666666666666667

In [ ]:
#numpy does not have a direct mode function
#mode =3*median - 2*mean
# maximum occurence of a elemnt 
# so to find mode we initialize the counter function for each element

In [38]:
mode=3*a-2*b
print('mode of array k is :',mode)

mode of array k is : 5.666666666666666


In [41]:
from collections import Counter
count=Counter(k)

In [42]:
count

Counter({0: 3, 1: 1, 2: 1, 3: 1, 4: 2, 5: 2, 6: 1, 7: 4, 8: 1, 9: 2})

In [44]:
count.most_common(1)

[(7, 4)]